import torch as th
s_embed = th.randn(3,2)
v_embed = th.randn(3,2)
print(s_embed)
print(v_embed)
print(s_embed * v_embed)
print((s_embed * v_embed).shape)
pos_sv = th.mean(th.sum(s_embed * v_embed, dim=1, keepdim=True),dim=1)
neg_s = th.mean(th.matmul(s_embed, s_embed.t()),dim=1)
print(pos_sv)
print(neg_s.shape)